/**
 * Measapp API
 * Home meassurements test app By Marton Szatzker
 *
 * OpenAPI spec version: v1
 * Contact: marton.szatzker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserData } from './userData';


export interface PagingResponseUserData { 
    totalCount?: number;
    result?: Array<UserData>;
}
