/**
 * Measapp API
 * Home meassurements test app By Marton Szatzker
 *
 * OpenAPI spec version: v1
 * Contact: marton.szatzker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Api test model for users
 */
export interface UserData { 
    userName?: string;
    emailAddress?: string;
    location?: string;
    admin?: boolean;
    executor?: boolean;
}
